### ISSUE TITLE
Implement authentication

### ISSUE THREAD

**Issue by JeremyCaney** [GoldSimSoftware/Website#19]
Previously, authentication was handled via **ASP.NET WebForms**'s Membership APIs. Those are overkill for how few users we have, and are very dated on top of it. We need to find an alternative solution that's simpler. 

### Open Questions
- [x] What are the best practices for implementing authentication on **ASP.NET Core**?

### Tasks
- [x] Implement **Azure OpenID Connect**
- [x] Expand to both _Ignia_ and _GoldSim_ directories
- [x] Apply authentication to _Editor_, _Licenses_
