### ISSUE TITLE
Update to use new `IHierarchicalTopicMappingService<>`

### ISSUE THREAD

**Issue by JeremyCaney** [GoldSimSoftware/Website#6]
**OnTopic** 3.8.0 makes a breaking change to the `LayoutController` by replacing the `ITopicMappingService` dependency with a new `IHierarchicalTopicMappingService<>` dependency. This centralizes a lot of the reusable logic for various `LayoutController` implementations while, importantly, also handing over control over caching to the _composition root_, thus allowing a single `LayoutController` to be used independent of whether or not the results need to be cached.

### Tasks
- [x] Update `LayoutController` to use `IHierarchicalTopicMappingService<>` 
- [x] Update `GoldSimControllerFactory` to construct proper dependency graph
- [x] Update `TopicViewModel` to auto-initialize `Children` so it can't be assigned to

**Comment by JeremyCaney** [comment]
This update has been completed as of #(dee9b95).

**Comment by JeremyCaney** [comment]
This update has been completed as of #(dee9b95).
